### ISSUE TITLE
Index out of range for multiple sources

### ISSUE THREAD

**Issue by Kelniimir** [Qionglu735/iwara_crawler#1]
Recently there's more and more authors which can be listed (list retrieved), but on download attempt, following occurred:

```
pi@Pi4-Secondary:~ $ python ~/Scripts/iwara_crawler.py
腿 玩 年 https://ecchi.iwara.tv/users/%E8%85%BF%20%E7%8E%A9%20%E5%B9%B4/videos
Reading Page No.1 ...
Video List:
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/Scripts/iwara_crawler.py", line 327, in <module>
    main(user["user_name"], user["file_prefix"], user["download_index"])
  File "/home/pi/Scripts/iwara_crawler.py", line 166, in main
    download_list.append(video_list[index])
IndexError: list index out of range
```
Running on Raspbian 10 Buster, on Raspberry 4B, headless, over SSH session.
Issue was occurring with one or few authors per month for last year (around the time I'm suing this project, my gratitude for sharing).
For last 2 weeks, basically every source I add shows this error.
Re-running prerequisites installation changed nothing.
Not using proxy (proxy IP commented with #), as my home setup doesn't have one, no other changes made, besides other authors added
Tested and experiencing it with following sources listed (as example, including original script sources, and my added sources):
```
    {"user_name": "vostman", "file_prefix": "", "download_index": [-1]},
    {"user_name": "The_Snowing-Fire", "file_prefix": "", "download_index": [-1, -2]},
    {"user_name": "mimimizu", "file_prefix": "", "download_index": [-1, -2]},
    {"user_name": "burton3rd", "file_prefix": "", "download_index": [-1, -2, -3]},
    {"user_name": "じさくのう", "file_prefix": "", "download_index": [-1, -2, -3]},
    {"user_name": "淫集院　笹", "file_prefix": "", "download_index": [-1, -2, -3]},
    {"user_name": "ViciNeko", "file_prefix": "", "download_index": [-1, -2]},
    {"user_name": "3Dimm Animations", "file_prefix": "", "download_index": [-1]},
    {"user_name": "sugokunemui", "file_prefix": "", "download_index": [-1]},
    {"user_name": "贾唯℡", "file_prefix": "AlZ", "download_index": [-1]},
    {"user_name": "HornOwl", "file_prefix": "", "download_index": [-1]},
    {"user_name": "kem_kem", "file_prefix": "", "download_index": [-1]},
    {"user_name": "lovemax", "file_prefix": "", "download_index": [-1]},
    {"user_name": "uAYx5C", "file_prefix": "", "download_index": []},
    {"user_name": "yaharuka", "file_prefix": "", "download_index": [-1, -2, -3]},
    {"user_name": "塩ひとつまみ", "file_prefix": "", "download_index": [-1]},
```
Leaving BLANK `[]}` as following shows same error
```
    {"user_name": "3Dimm Animations", "file_prefix": "", "download_index": []},
```
Leaving positive value `[1]}` to download specific video, not last or pre-last shows same error, with traceback to different row, but same function.
```
pi@Pi4-Secondary:~ $ python ~/Scripts/iwara_crawler.py
3Dimm Animations https://ecchi.iwara.tv/users/3Dimm%20Animations/videos
Reading Page No.1 ...
Video List:
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/Scripts/iwara_crawler.py", line 327, in <module>
    main(user["user_name"], user["file_prefix"], user["download_index"])
  File "/home/pi/Scripts/iwara_crawler.py", line 164, in main
    download_list.append(video_list[index - 1])
IndexError: list index out of range
```
Unfortunately, my skills at Python are not sufficient to understand and fix it myself, I'm just a beginner.

**Comment by Qionglu735** [comment]
It's not your problem.
Iwara.com update to a new version, which require login session to grab download link. So this script is not working anymore.

**Comment by Kelniimir** [comment]
Unfortunate.
Thank you for explanation.
I noticed visual changes on web site, but not realized there are changes under the hood as well.

I might be daring to ask but... Do you still maintain this script? May I expect it will work again at some point?

Or it was a hobby project, and you don't plan reworking it?

**Comment by Qionglu735** [comment]
its on my plan. 
but for now i still can't figure out how it work. Can't promise anything yet.

**Comment by Qionglu735** [comment]
try iwara_crawler_v2.py
