### ISSUE TITLE
Coding not set (possible environment differences), and syntax errors

### ISSUE THREAD

**Issue by Kelniimir** [Qionglu735/iwara_crawler#2]
Unfortunately, on attempt to run on Raspbian, using original file `iwara_crawler_v2.py` (prior editing to add my sources), i get following:

```
File "/home/pi/Scripts/iwara_crawler_v2.py", line 33
SyntaxError: Non-ASCII character '\xe5' in file /home/pi/Scripts/iwara_crawler_v2.py on line 33, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
After searching for solution i add this to beginning of file as per: [Python-no-encoding-declared](https://stackoverflow.com/questions/44253516/no-encoding-declared)
`# -*- coding: utf-8 -*-`

After adding this, I get another error:

```
  File "/home/pi/Scripts/iwara_crawler_v2.py", line 79
    def get(self, url, params=None, **_kwargs) -> requests.Response:
                                               ^
SyntaxError: invalid syntax
```

I'm not able to understand why this particular dash is a syntax violation.
It seems whole `->` part is not recognized as "reverse annotation"?
Studying [PEP3107](https://peps.python.org/pep-3107/), didn't quite figured what needed to be changed for now...

Platform:
```
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
Python 2.7
```

**Comment by Qionglu735** [comment]
You need Python 3. I'm using 3.11.

And you may need to download the "chromedriver" with correct platform / version manually. The auto install script is not working for now.
https://googlechromelabs.github.io/chrome-for-testing/

**Comment by Kelniimir** [comment]
Good evening,

Thank you fro your response.
I am indeed running Python 2.7.16 and 3.7.3.
Would install 3.11 or 3.12 and try again, with original script, and with my corrections.

Also, will check for correct Chromedriver 👍

**Comment by Kelniimir** [comment]
Issues listed above disappeared after properly switching to Python3
