### ISSUE TITLE
For iwara_crawler_v2, selenium/fake-useragent aren't part of "requirements.txt"

### ISSUE THREAD

**Issue by Kelniimir** [Qionglu735/iwara_crawler#3]
Hello there.

Please remember following files aren't part of requirements, and cause script v2 execution to fail, unless installed manually.
Maybe worth mention in text, or add to requirements.txt
 
- `selenium` (can be installed with `sudo pip3 install selenium`)
- `fake-useragent` (can be installed with `sudo pip3 install fake-useragent`)

Example of my attempt to run script v2
```
[user]@Pi4-Primary:~/Scripts $ python3 ~/Scripts/iwara_crawler_v2_mod.py
Traceback (most recent call last):
  File "/home/pi/Scripts/iwara_crawler_v2_mod.py", line 2, in <module>
    from fake_useragent import UserAgent
ModuleNotFoundError: No module named 'fake_useragent'
```

After installation of `fake-useragent` execution gets through this step.

**Comment by Qionglu735** [comment]
Wow thanks. I will update the req.txt

**Comment by Qionglu735** [comment]
Req should be fixed now.
